In [1]:
import numpy as np

In [2]:
np.random.seed(100)

In [3]:
np.random.randint(0,100,10)

array([ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98])

In [4]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
mat[5,2]

52

In [6]:
mat[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [7]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [9]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.graph_objs as go
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
np.random.seed(42)
random_x = np.random.randint(1,101,100)
random_y = np.random.randint(1,101,100)

In [12]:
data = [go.Scatter(x=random_x, 
                   y=random_y, 
                   mode='markers', 
                   marker=dict(
                   size=12,
                   color='rgb(204,52,153)',
                   symbol='pentagon',
                   line={'width':2}))]

layout = go.Layout(title='Scatter Plot',
                  xaxis={'title':'My X-axis'},
                  yaxis=dict(title='My Y axis'),
                  hovermode='closest')

fig = go.Figure(data=data, layout=layout)

pyo.plot(fig, filename='scatter.html')

'scatter.html'

In [13]:
#Line chart
x_values = np.linspace(0,1,100)
y_values = np.random.randn(100)

In [14]:
trace0=go.Scatter(x = x_values, y = y_values+5,
                mode='markers', name='markers')

trace1=go.Scatter(x = x_values, y = y_values,
                mode='lines', name='lines')

trace2=go.Scatter(x = x_values, y = y_values-5,
                mode='lines+markers', name='L+M')

data = [trace0,trace1, trace2]

layout = go.Layout(title='Line Charts')

fig = go.Figure(data=data, layout=layout)

pyo.plot(fig)

'temp-plot.html'

In [15]:
df = pd.read_csv('Data/nst-est2017-alldata.csv')
df.head()

SUMLEV REGION DIVISION  STATE              NAME  CENSUS2010POP  \
0    10.0      0        0    0.0     United States    308745538.0   
1    20.0      1        0    0.0  Northeast Region     55317240.0   
2    20.0      2        0    0.0    Midwest Region     66927001.0   
3    20.0      3        0    0.0      South Region    114555744.0   
4    20.0      4        0    0.0       West Region     71945553.0   

   ESTIMATESBASE2010  POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  ...  \
0        308758105.0      309338421.0      311644280.0      313993272.0  ...   
1         55318350.0       55388349.0       55642659.0       55860261.0  ...   
2         66929794.0       66973360.0       67141501.0       67318295.0  ...   
3        114563024.0      114869241.0      116060993.0      117291728.0  ...   
4         71946937.0       72107471.0       72799127.0       73522988.0  ...   

   RDOMESTICMIG2015  RDOMESTICMIG2016  RDOMESTICMIG2017  RNETMIG2011  \
0          0.000000          0.000000          0.000000     2.720900   
1         -6.103092         -6.619089         -5.559570     1.467950   
2         -3.458531         -3.307295         -2.304640    -1.187519   
3          3.788037          3.592695          2.900528     5.544289   
4          1.613450          2.099001          1.475519     2.798796   

   RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015  RNETMIG2016  \
0     2.920371     2.883643     3.173228     3.516743     3.513394   
1     0.779137     0.605873    -0.082832    -0.903931    -1.307503   
2    -1.010696    -0.120354    -0.752477    -1.323952    -1.160735   
3     5.831747     5.362083     6.317310     7.336162     7.113818   
4     3.521423     3.396627     4.163576     5.067452     5.488965   

   RNETMIG2017  
0     3.423941  
1    -0.288930  
2    -0.191323  
3     6.304010  
4     4.737979  

[5 rows x 121 columns]

In [16]:
df2 = df[df['DIVISION']=='1']
df2.set_index('NAME', inplace=True)
list_of_pop_col = [col for col in df2.columns if col.startswith('POP')]
df2 = df2[list_of_pop_col]

In [17]:
df2

POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
NAME                                                               
Connecticut          3580171.0        3591927.0        3597705.0   
Maine                1327568.0        1327968.0        1328101.0   
Massachusetts        6564943.0        6612178.0        6659627.0   
New Hampshire        1316700.0        1318345.0        1320923.0   
Rhode Island         1053169.0        1052154.0        1052761.0   
Vermont               625842.0         626210.0         625606.0   

               POPESTIMATE2013  POPESTIMATE2014  POPESTIMATE2015  \
NAME                                                               
Connecticut          3602470.0        3600188.0        3593862.0   
Maine                1327975.0        1328903.0        1327787.0   
Massachusetts        6711138.0        6757925.0        6794002.0   
New Hampshire        1322622.0        1328684.0        1330134.0   
Rhode Island         1052784.0        1054782.0        1055916.0   
Vermont               626044.0         625665.0         624455.0   

               POPESTIMATE2016  POPESTIMATE2017  
NAME                                             
Connecticut          3587685.0        3588184.0  
Maine                1330232.0        1335907.0  
Massachusetts        6823721.0        6859819.0  
New Hampshire        1335015.0        1342795.0  
Rhode Island         1057566.0        1059639.0  
Vermont               623354.0         623657.0

In [18]:
data = [go.Scatter(x=df2.columns, y=df2.loc[name], mode='lines', name=name) for name in df2.index]

pyo.plot(data)

'temp-plot.html'

In [19]:
#Exercise
df = pd.read_csv('Data/2010YumaAZ.csv')
df.head()

LST_DATE      DAY LST_TIME  T_HR_AVG
0  20100601  TUESDAY     0:00      25.2
1  20100601  TUESDAY     1:00      24.1
2  20100601  TUESDAY     2:00      24.4
3  20100601  TUESDAY     3:00      24.9
4  20100601  TUESDAY     4:00      22.8

In [20]:
days = df.DAY.unique().tolist()
days

['TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', 'MONDAY']

In [21]:
#Use for oop for data list
# data =[]

# for day in days:
#     trace = go.Scatter(x=df.LST_TIME, y=df.loc[df.DAY==day].T_HR_AVG, mode='lines', name=day)
#     data.append(trace)
data = [go.Scatter(x=df.LST_TIME, y=df.loc[df.DAY==day].T_HR_AVG, mode='lines', name=day) for day in df.DAY.unique()]
    
layout = go.Layout(title='Daily Temperateure Avgs')

fig = go.Figure(data=data, layout=layout)

pyo.plot(fig)

'temp-plot.html'

In [24]:
#Bar charts - For Categorical data
df = pd.read_csv('Data/2018WinterOlympics.csv')
df.head()

Rank            NOC  Gold  Silver  Bronze  Total
0     1         Norway    14      14      11     39
1     2        Germany    14      10       7     31
2     3         Canada    11       8      10     29
3     4  United States     9       8       6     23
4     5    Netherlands     8       6       6     20

In [29]:
data = [go.Bar(x = df.NOC, y = df[col], name=col, marker={'color':colors}) for col,colors in zip(['Gold','Silver','Bronze'],['#FFD700', '#9EA0A1', '#CD7F32'])]
    
layout = go.Layout(title='Medals')

fig = go.Figure(data=data, layout=layout)

pyo.plot(fig)

'temp-plot.html'

In [28]:
data = [go.Bar(x = df.NOC, y = df[col], name=col, marker={'color':colors}) for col,colors in zip(['Gold','Silver','Bronze'],['#FFD700', '#9EA0A1', '#CD7F32'])]
    
layout = go.Layout(title='Medals',barmode='stack')

fig = go.Figure(data=data, layout=layout)

pyo.plot(fig)

'temp-plot.html'

In [40]:
#Exercises
df = pd.read_csv('Data/mocksurvey.csv', index_col=0)
df.head()

Strongly Agree  Somewhat Agree  Neutral  Somewhat Disagree  \
Question 1            0.45            0.25     0.10               0.12   
Question 2            0.12            0.07     0.48               0.18   
Question 3            0.05            0.22     0.19               0.23   

            Strongly Disagree  
Question 1               0.08  
Question 2               0.15  
Question 3               0.31

In [41]:
data = [go.Bar(x = df.index, y = df[col], name=col, marker={'color':colors}) for col,colors in zip(df.columns,['#00FFFF', '#9EA0A1', '#daebdd','#9EB0A1', '#ffe9e8'])]
    
layout = go.Layout(title='Medals',barmode='stack')

fig = go.Figure(data=data, layout=layout)

pyo.plot(fig)

'temp-plot.html'

In [43]:
data = [go.Bar(x = df[col], y = df.index, name=col, orientation='h',marker={'color':colors}) for col,colors in zip(df.columns,['#00FFFF', '#9EA0A1', '#daebdd','#9EB0A1', '#ffe9e8'])]
    
layout = go.Layout(title='Medals',barmode='stack')

fig = go.Figure(data=data, layout=layout)

pyo.plot(fig)

'temp-plot.html'

In [44]:
#Bubble chart
df = pd.read_csv('Data/mpg.csv')
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model_year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [58]:
data = [go.Scatter(x=df['horsepower'],
                  y=df['mpg'],
                  text =df['name'],
                  mode='markers',
                  marker=dict(size=df['weight']/150, 
                              color=df.cylinders,
                             showscale=True))]
layout = go.Layout(title='Bubble Chart', hovermode='closest')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [64]:
#Box Plots
y = [1,14,14,15,16,18,18,19,19,20,20,23,24,26,27,27,28,29,33,54]
#Pointpos is where the scatter plot(-2,-1,0,1,2) to appear and jitter is the spread
data = [go.Box(y=y, boxpoints='all', jitter=0.3, pointpos=2.0)]
pyo.plot(data)

'temp-plot.html'

In [65]:
#show only the points for outliers
data = [go.Box(y=y, boxpoints='outliers')]
pyo.plot(data)

'temp-plot.html'

In [67]:
snodgrass = [.209,.205,.196,.210,.202,.207,.224,.223,.220,.201]
twain = [.225,.262,.217,.240,.230,.229,.235,.217]

data = [go.Box(y=snodgrass, name='Snodgrass'),
       go.Box(y=twain, name='Twain')]
pyo.plot(data)

'temp-plot.html'

In [68]:
df = pd.read_csv('Data/abalone.csv')
df.head()

sex  length  diameter  height  whole_weight  shucked_weight  viscera_weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   shell_weight  rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [70]:
sample1 = np.random.choice(df['rings'], 30, replace=False)
sample2 = np.random.choice(df['rings'], 20, replace=False)
data = [go.Box(y=sample1, name='sample1'),
       go.Box(y=sample2, name='sample2')]
pyo.plot(data)

'temp-plot.html'

In [77]:
#Histogram - Overall distribution of continuous data over an interval - bin - intervals - count no of occurance of data for each bins
import plotly.offline as pyo
import plotly.graph_objs as go
import pandas as pd

df = pd.read_csv('Data/mpg.csv')
data = [go.Histogram(x=df['mpg'], xbins=dict(start=0, end=50, size=2))]


layout = go.Layout(title='Histogram')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [80]:
df = pd.read_csv('Data/abalone.csv')
data = [go.Histogram(x=df['length'], xbins=dict(start=0, end=1, size=0.02))]


layout = go.Layout(title='Histogram')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [84]:
#Distribution plot - three plots on top of each other - hist, rug, KDE
import plotly.offline as pyo
import plotly.figure_factory as ff
import numpy as np

x1 = np.random.randn(200)-2
x2 = np.random.randn(200)
x3 = np.random.randn(200)+2
x4 = np.random.randn(200)+4

hist_data=[x1,x2,x3,x4]
group_labels = ['X1','X2','X3','X4']

fig = ff.create_distplot(hist_data, group_labels, bin_size=[.2,.1,.3,.4])
pyo.plot(fig)

'temp-plot.html'

In [87]:
hist_data=[snodgrass, twain]
group_labels = ['snodgrass','twain']

fig = ff.create_distplot(hist_data, group_labels, bin_size=[.005,.005])
pyo.plot(fig)

'temp-plot.html'

In [88]:
df = pd.read_csv('Data/iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [93]:
df['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [94]:
hist_data=[df[df['class'] == 'Iris-setosa']['petal_length'],df[df['class'] == 'Iris-versicolor']['petal_length'],df[df['class'] == 'Iris-virginica']['petal_length']]
group_labels = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

fig = ff.create_distplot(hist_data, group_labels)
pyo.plot(fig)

'temp-plot.html'

In [97]:
#Heat Maps - for both continuous and categorical features
df = pd.read_csv('Data/2010SantaBarbaraCA.csv')
data = [go.Heatmap(x=df.DAY, 
                   y=df.LST_TIME, 
                   z=df.T_HR_AVG.values.tolist(),
                  colorscale='Jet')]

layout = go.Layout(title='Temp Heatmap')
fig = go.Figure(data, layout)
pyo.plot(fig)

'temp-plot.html'

In [103]:
#Subplots
from plotly import tools
df1 = pd.read_csv('Data/2010SitkaAK.csv')
df2 = pd.read_csv('Data/2010SantaBarbaraCA.csv')
df3 = pd.read_csv('Data/2010YumaAZ.csv')
#shared_yaxes - sharing y axis or seperate y axis if True or False in this field
trace1 = go.Heatmap(x=df1.DAY, 
                   y=df1.LST_TIME, 
                   z=df1.T_HR_AVG.values.tolist(),
                  colorscale='Jet', zmin=5, zmax=40)

trace2 = go.Heatmap(x=df2.DAY, 
                   y=df2.LST_TIME, 
                   z=df2.T_HR_AVG.values.tolist(),
                  colorscale='Jet', zmin=5, zmax=40)

trace3 = go.Heatmap(x=df3.DAY, 
                   y=df3.LST_TIME, 
                   z=df3.T_HR_AVG.values.tolist(),
                  colorscale='Jet', zmin=5, zmax=40)
fig = tools.make_subplots(rows=1, cols=3, subplot_titles=['sitka', 'california','Yutah'],
                         shared_yaxes=False)
fig.append_trace(trace1,1,1)
fig.append_trace(trace2,1,2)
fig.append_trace(trace3,1,3)

fig['layout'].update(title='Temperature for 3 sities')
pyo.plot(fig)

This is the format of your plot grid:
[ (1,1) x1,y1 ]  [ (1,2) x2,y2 ]  [ (1,3) x3,y3 ]



'temp-plot.html'

In [105]:
df= pd.read_csv('Data/flights.csv')
data = [go.Heatmap(x=df.year, 
                   y=df.month, 
                   z=df.passengers.values.tolist(),
                  colorscale='Jet')]

layout = go.Layout(title='Flight Data Heatmap')
fig = go.Figure(data, layout)
pyo.plot(fig)

'temp-plot.html'

Dash Dashboard Basics

In [117]:
#Two parts - Dash html components and Dash core components
import dash
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash()

colors={'backgroud':'#111111','text':'#7FDBFF'}

app.layout= html.Div(children=[html.H1('Hello Dash!'),
                              html.Div('Dash: Web Dashboards in python'),
                              dcc.Graph(id='example',
                                       figure={'data':[
                                           {'x':[1,2,3],'y':[4,1,2],'type':'bar','name':'SF'},
                                           {'x':[1,2,3],'y':[2,4,5],'type':'bar','name':'NYC'}
                                       ],
                                              'layout':{
                                                  'title':'BAR PLOTS'
                                              }})])

app.run_server()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Aug/2019 17:27:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 17:27:17] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 17:27:17] "GET /_dash-dependencies HTTP/1.1" 200 -


In [119]:
app = dash.Dash()

colors={'backgroud':'#111111','text':'#7FDBFF'}

app.layout= html.Div(children=[html.H1('Hello Dash!',style={'textAlign':'center',
                                                           'color':colors['text']}),
                              dcc.Graph(id='example',
                                       figure={'data':[
                                           {'x':[1,2,3],'y':[4,1,2],'type':'bar','name':'SF'},
                                           {'x':[1,2,3],'y':[2,4,5],'type':'bar','name':'NYC'}
                                       ],
                                              'layout':{
                                                  'plot_bgcolor':colors['backgroud'],
                                                  'paper_bgcolor':colors['backgroud'],
                                                  'font':{'color':colors['text']},
                                                  'title':'BAR PLOTS'
                                              }})],style={'backgroundColor':colors['backgroud']})

app.run_server()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Aug/2019 17:31:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 17:31:31] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 17:31:31] "GET /_dash-dependencies HTTP/1.1" 200 -


In [125]:
#Inserting Plots into the dashboard
app = dash.Dash()
np.random.seed(42)
random_x = np.random.randint(1,101,100)
random_y = np.random.randint(1,101,100)

app.layout=html.Div([dcc.Graph(id='scatterplot',
                              figure={'data':[go.Scatter(x=random_x, y=random_y, mode='markers',marker={'size':12,
                                                                                                       'color':'rgb(51, 204, 153)',
                                                                                                       'symbol':'pentagon',
                                                                                                       'line':{'width':2}}),
                                             ],
                                  'layout':go.Layout(title='My Scatterplot',xaxis={'title':'Some X title'})})])
app.run_server()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Aug/2019 17:58:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 17:58:48] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 17:58:48] "GET /_dash-dependencies HTTP/1.1" 200 -


In [128]:
#Inserting multiple Plots into the dashboard
app = dash.Dash()
np.random.seed(42)
random_x = np.random.randint(1,101,100)
random_y = np.random.randint(1,101,100)

app.layout=html.Div([dcc.Graph(id='scatterplot1',
                              figure={'data':[go.Scatter(x=random_x, y=random_y, mode='markers',marker={'size':12,
                                                                                                       'color':'rgb(51, 204, 153)',
                                                                                                       'symbol':'pentagon',
                                                                                                       'line':{'width':2}}),
                                             ],
                                  'layout':go.Layout(title='My Scatterplot 1',xaxis={'title':'Some X title'})}),
                    dcc.Graph(id='scatterplot2',
                              figure={'data':[go.Scatter(x=random_x, y=random_y, mode='markers',marker={'size':12,
                                                                                                       'color':'rgb(200, 204, 53)',
                                                                                                       'symbol':'circle',
                                                                                                       'line':{'width':3}}),
                                             ],
                                  'layout':go.Layout(title='My Scatterplot 2',xaxis={'title':'Some X title'})})])
app.run_server()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Aug/2019 18:02:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 18:02:04] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 18:02:04] "GET /_dash-dependencies HTTP/1.1" 200 -


In [135]:
#Exercise
df = pd.read_csv('Data/OldFaithful.csv')
app = dash.Dash()
np.random.seed(42)
app.layout=html.Div([dcc.Graph(id='old_faithful',
                              figure={'data':[go.Scatter(x=df.X, y=df.Y, mode='markers',marker={'size':6,
                                                                                                       'color':'rgb(51, 204, 153)',
                                                                                                       'line':{'width':2}}),
                                             ],
                                  'layout':go.Layout(title='Old Faithful Eruption Duration',
                                                     xaxis={'title':'Duration of eruption(Minutes)'},
                                                    yaxis={'title':'Interval to next eruption(Minutes)'})})])
app.run_server()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Aug/2019 18:10:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 18:10:49] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 18:10:49] "GET /_dash-dependencies HTTP/1.1" 200 -


In [143]:
#Dash HTML components
import dash
import dash_html_components as html

app = dash.Dash()
#div([]) - multiple item, div() - single item
app.layout = html.Div(['This is the outermost div!',
                      html.Div('This is an inner div!',
                              style={'color':'red', 'border':'2px red solid'}),
                      html.Div(['Another Div!'],
                              style={'color':'blue', 'border':'2px blue solid'})],
                     style={'color':'green', 'border':'2px green solid'})

app.run_server()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Aug/2019 21:36:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 21:36:04] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 21:36:04] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 21:36:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 21:36:43] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 21:36:43] "GET /_dash-dependencies HTTP/1.1" 200 -


In [154]:
#Dash Core components
import dash
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash()

app.layout = html.Div([
    html.Label('Dropdown'),
    dcc.Dropdown(options=[{'label':'New York City', 'value':'NYC'},
                         {'label':'Sanfrancisco', 'value':'SF'},
                         {'label':'Washington DC', 'value':'DC'}],
                value='SF'),#Default value
    html.P(html.Label('Slider')),
    dcc.Slider(min=-10, max=10, step=0.5,value=0, marks={i: i for i in range(-10,10)}),
    html.P(html.Label('Some Radio Items')),
    dcc.RadioItems(options=[{'label':'New York City', 'value':'NYC'},
                         {'label':'Sanfrancisco', 'value':'SF'},
                         {'label':'Washington DC', 'value':'DC'}],
                value='SF')#Default value             
])

app.run_server()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)


#Markdown in Dash - http://commonmark.org/help
#help(), pydoc - Help

In [157]:
#Callbacks - connecting the components for interaction
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash()

app.layout = html.Div([dcc.Input(id='my-id', value='Initial_Text', type='Text'),
                       html.Div(id='my-div')])

app.run_server()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Aug/2019 22:55:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 22:55:30] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2019 22:55:30] "GET /_dash-dependencies HTTP/1.1" 200 -
